In [1]:
#importing libraries
import pandas as pd
import numpy as np

<B>
    
Q1. Write a function so that the columns of the output matrix are powers of the input
vector.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [15]:
#creating a matrix with output columns based on input vector (N)

x=np.array([1,2,3,4])
N=5

print("Vander matrix of the input array in decreasing order of powers:","\n")
matrix=np.vander(x,N,increasing=False)
print(matrix)

Vander matrix of the input array in decreasing order of powers: 

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]


In [16]:
print("Vander matrix of the input array in increasing order of powers:","\n")
matrix=np.vander(x,N,increasing=True)
print(matrix)

Vander matrix of the input array in increasing order of powers: 

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]]


<B>
_______________________________________________________________________________________________________________________________    
Q2. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.


In [38]:
#function for moving average
def moving_avg(mylist,N):
    asum=np.cumsum(mylist, dtype=float) #gets cumulative sum
    
    asum[N:]=asum[N:]-asum[:-N]   #breaking the array with "N" and subtracting to get results
    return asum[N-1:]/N
    
mylist= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
mylist1=np.array(mylist)
N=3
#moving average with rounding off
mov_avg = np.array(moving_avg(mylist1,N=3)).round(2)

In [34]:
mov_avg = np.array(moving_avg(mylist1,N=3)).round(2)

print("The moving average of the sequence with the rolling window size 3 is:","\n""\n", mov_avg)

The moving average of the sequence with the rolling window size 3 is: 

 [  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
